#!/usr/bin/node

const log = console.log;
log('CPU',process.arch);
log('OS',process.platform);
log('PID',process.pid);
log('exePath:%s\n',process.execPath);
log('node.js ver:',process.version);
log('uid:',process.getuid());
log('gid',process.getgid());
 






